parameters:
    novaway.fmb.twigextension.class: Novaway\Bundle\FileManagementBundle\Twig\Extension\FileManagementExtension
    novaway.fmb.form.type.image.extension.class: Novaway\Bundle\FileManagementBundle\Form\Extensions\ImageTypeExtension
    novaway.fmb.form.type.image.class: Novaway\Bundle\FileManagementBundle\Form\Type\ImageType

services:
    novaway.fmb.form.type.image:
        class: "%novaway.fmb.form.type.image.class%"
        arguments: ["%novaway.fmb.webdir%"]
        tags:
            - { name: form.type }

    novaway.fmb.form.type.image.extension:
        class: "%novaway.fmb.form.type.image.extension.class%"
        tags:
            - { name: form.type_extension, extended_type: Novaway\Bundle\FileManagementBundle\Form\Extensions\ImageTypeExtension }

    novaway.fmb.twig_extension:
        class : "%novaway.fmb.twigextension.class%"
        arguments : ["@router", "%novaway.fmb.webdir%"]
        tags:
            - { name: twig.extension }
